######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 29 23:17:30 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += KeysWidget.h MainWindow.h
SOURCES += KeysWidget.cpp main.cpp MainWindow.cpp
